# Generated by Django 4.2.5 on 2023-09-12 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='', max_length=100)),
                ('l_name', models.CharField(default='', max_length=100)),
                ('data_of_birth', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Master',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(default='', max_length=100)),
                ('time_of_order', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
